import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Soft Grunge
// Pale Lilac (#D8BFD8)
// Muted Teal (#4C9085)
// Charcoal Gray (#333333)
// Off-White (#F5F5F5)

/*
Monochrome with a Twist - HELL YEAH
Charcoal (#333333)
Silver (#C0C0C0)
Bright Red (#FF0000)
Ivory (#FFFFF0)
*/

/*Soft Grunge - NOPE
Pale Lilac (#D8BFD8)
Muted Teal (#4C9085)
Charcoal Gray (#333333)
Off-White (#F5F5F5)*/

/*Minimalist Vibrancy
Bright Yellow (#FFD300)
Pastel Purple (#C6A7E2)
Deep Navy (#1A1A40)
Soft Gray (#F2F2F2)*/

/*Retro Futurism
Vivid Purple (#9B5DE5)
Bright Turquoise (#00F5D4)
Coral Pink (#FF6F61)
Midnight Blue (#0C0F0A*/

